meeting:
  topic: "Как предпринимателю снизить налоги"
  link: "https://zoom.us/placeholder-link"
  time: "11:00"

timezone: "Europe/Moscow"

schedule:
  invitation_day: "monday"
  invitation_time: "10:00"
  
  reminder_1_day: "wednesday"
  reminder_1_time: "09:00"
  
  reminder_2_day: "wednesday"
  reminder_2_time: "10:40"

# Upcoming meetings schedule
upcoming_meetings:
  - date: "2025-11-13"
    topic: "Как автоматизировать бухгалтерию предпринимателю"
    link: "https://zoom.us/j/meeting-1"
    time: "11:00"
  
  - date: "2025-11-20"
    topic: "Как снизить налоговую нагрузку в 2025"
    link: "https://zoom.us/j/meeting-2"
    time: "11:00"
  
  - date: "2025-11-27"
    topic: "Всё, что нужно знать о налоговых проверках"
    link: "https://zoom.us/j/meeting-3"
    time: "11:00"
  
  - date: "2025-12-04"
    topic: "Взносы ИП: что изменится в 2026"
    link: "https://zoom.us/j/meeting-4"
    time: "11:00"
  
  - date: "2025-12-11"
    topic: "ТОП-5 ошибок предпринимателей при работе с ФНС"
    link: "https://zoom.us/j/meeting-5"
    time: "11:00"
  
  - date: "2025-12-18"
    topic: "Как выбрать форму налогообложения в 2026"
    link: "https://zoom.us/j/meeting-6"
    time: "11:00"

# Admin IDs
admins:
  - 7742103512  # @BotBrokerService
  - 0  # @t8tata - будет определен после /start

